In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset['classification_yes']

In [9]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [10]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

# 1. Create a pipeline with a MinMaxScaler to support MultinomialNB
pipeline = Pipeline([
    ('scaler', MinMaxScaler()),
    ('classifier', GaussianNB()) # Placeholder
])

# 2. Define the search grids for all three Naive Bayes models
param_grid = [
    {
        'classifier': [GaussianNB()],
        'classifier__var_smoothing': [1e-9, 1e-8, 1e-7]
    },
    {
        'classifier': [MultinomialNB()],
        'classifier__alpha': [0.1, 0.5, 1.0, 2.0]
    },
    {
        'classifier': [BernoulliNB()],
        'classifier__alpha': [0.1, 0.5, 1.0, 2.0]
    }
]

# 3. Create the GridSearchCV instance
grid = GridSearchCV(
    estimator=pipeline, 
    param_grid=param_grid, 
    refit=True, 
    verbose=3, 
    n_jobs=-1, 
    scoring='f1_weighted'
)

# 4. Fit the multi-model grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 11 candidates, totalling 55 fits

GridSearchCV(estimator=Pipeline(steps=[('scaler', MinMaxScaler()),
                                       ('classifier', GaussianNB())]),
             n_jobs=-1,
             param_grid=[{'classifier': [GaussianNB()],
                          'classifier__var_smoothing': [1e-09, 1e-08, 1e-07]},
                         {'classifier': [MultinomialNB()],
                          'classifier__alpha': [0.1, 0.5, 1.0, 2.0]},
                         {'classifier': [BernoulliNB()],
                          'classifier__alpha': [0.1, 0.5, 1.0, 2.0]}],
             scoring='f1_weighted', verbose=3)

In [12]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [13]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'classifier': GaussianNB(), 'classifier__var_smoothing': 1e-08}: 0.9775556904684072

In [14]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 3 79]]

In [15]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

In [16]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

1.0

In [17]:
table=pd.DataFrame.from_dict(re)

In [18]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_classifier,param_classifier__var_smoothing,param_classifier__alpha,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.061421,0.014523,0.044788,0.009388,GaussianNB(),1.000000e-09,NaN,"{'classifier': GaussianNB(), 'classifier__var_...",0.981569,0.981014,0.962573,1.000000,0.981217,0.981275,0.011837,3
1,0.062827,0.012316,0.036747,0.006289,GaussianNB(),1.000000e-08,NaN,"{'classifier': GaussianNB(), 'classifier__var_...",0.981569,0.981014,0.981217,1.000000,0.981217,0.985003,0.007500,1
2,0.038479,0.025999,0.026125,0.009940,GaussianNB(),1.000000e-07,NaN,"{'classifier': GaussianNB(), 'classifier__var_...",0.981569,0.981014,0.981217,1.000000,0.981217,0.985003,0.007500,1
3,0.045881,0.008253,0.029728,0.004065,MultinomialNB(),NaN,0.1,"{'classifier': MultinomialNB(), 'classifier__a...",0.981569,0.962264,0.962573,0.981217,0.981217,0.973768,0.009268,5
4,0.038880,0.004258,0.035132,0.007112,MultinomialNB(),NaN,0.5,"{'classifier': MultinomialNB(), 'classifier__a...",0.981569,0.962264,0.962573,0.981217,0.981217,0.973768,0.009268,5
5,0.048390,0.004184,0.034690,0.004976,MultinomialNB(),NaN,1.0,"{'classifier': MultinomialNB(), 'classifier__a...",0.981569,0.962264,0.962573,0.981217,0.981217,0.973768,0.009268,5
6,0.040657,0.004242,0.029448,0.002013,MultinomialNB(),NaN,2.0,"{'classifier': MultinomialNB(), 'classifier__a...",0.981569,0.962264,0.962573,0.962573,0.981217,0.970039,0.009272,8
7,0.035208,0.002448,0.028193,0.001463,BernoulliNB(),NaN,0.1,"{'classifier': BernoulliNB(), 'classifier__alp...",0.981569,0.981014,0.962573,1.000000,0.981217,0.981275,0.011837,3
8,0.036885,0.007195,0.050941,0.007066,BernoulliNB(),NaN,0.5,"{'classifier': BernoulliNB(), 'classifier__alp...",0.926978,0.962264,0.925524,0.981217,0.981217,0.955440,0.024821,9
9,0.056367,0.006286,0.047702,0.005489,BernoulliNB(),NaN,1.0,"{'classifier': BernoulliNB(), 'classifier__alp...",0.926978,0.962264,0.888515,0.962573,0.981217,0.944309,0.032959,10
10,0.057353,0.002756,0.040037,0.005359,BernoulliNB(),NaN,2.0,"{'classifier': BernoulliNB(), 'classifier__alp...",0.926978,0.943699,0.888515,0.962573,0.981217,0.940597,0.031751,11

In [20]:
age_input=float(input("Age:"))
bp_input= float(input("bp:"))
al_input=int(input("al:"))
su_input=int(input("su:"))
bgr_input=int(input("bgr:"))
bu_input=int(input("bu:")) 
sc_input=int(input("sc:")) 
sod_input=int(input("sod:"))
pot_input=int(input("pot:")) 
hrmo_input=int(input("hrmo:")) 
pcv_input=int(input("pcv:"))
wc_input=int(input("wc:"))
rc_input=int(input("rc:"))
sg_b_input=int(input("sg_b:"))
sg_c_input=int(input("sg_c:"))
sg_d_input=int(input("sg_d:"))
sg_e_input=int(input("sg_e:"))
rbc_normal_input=int(input("rbc_normal:"))
pc_normal_input=int(input("pc_normal:"))
pcc_present_input=int(input("pcc_present:"))
ba_present_input=int(input("ba_present:"))
htn_yes_input=int(input("htn_yes:"))
dm_yes_input=int(input("dm_yes:"))
cad_yes_input=int(input("cad_yes:"))
appet_yes_input=int(input("appet_yes:"))
pe_yes_input=int(input("pe_yes:"))
ane_yes_input=int(input("ane_yes:"))

Age: 20
bp: 21
al: 21
su: 10
bgr: 2
bu: 4
sc: 5
sod: 5
pot: 5
hrmo: 4
pcv: 5
wc: 6
rc: 2
sg_b: 5
sg_c: 2
sg_d: 8
sg_e: 2
rbc_normal: 1
pc_normal: 5
pcc_present: 6
ba_present: 8
htn_yes: 4
dm_yes: 2
cad_yes: 8
appet_yes: 2
pe_yes: 5
ane_yes: 5

In [25]:
Future_Prediction=grid.predict([[bp_input, age_input, al_input,su_input,bgr_input,bu_input ,sc_input,sod_input,
pot_input,hrmo_input, pcv_input, wc_input, rc_input, sg_b_input, sg_c_input, sg_d_input, sg_e_input, rbc_normal_input, pc_normal_input, pcc_present_input,
ba_present_input, htn_yes_input, dm_yes_input, cad_yes_input, appet_yes_input, pe_yes_input, ane_yes_input]])

C:\Users\swadh\anaconda4\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

In [27]:
print(Future_Prediction)

[1]